# Generated by Django 4.0 on 2022-01-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFishapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freg',
            name='adrs',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
