# Generated by Django 4.0 on 2022-01-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0006_rfish'),
        ('webFishapp', '0002_freg_adrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fwcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishapp.pfish')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webFishapp.freg')),
            ],
        ),
    ]
