# Generated by Django 4.0 on 2022-01-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFishapp', '0003_fwcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='fwcart',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fwcart',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
