# Generated by Django 4.0 on 2022-01-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webFishapp', '0004_fwcart_price_fwcart_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fwcart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='fwcart',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='fwcart',
            name='weight',
        ),
    ]
