# Generated by Django 4.0 on 2022-01-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFishapp', '0005_remove_fwcart_price_remove_fwcart_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fview_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('subject', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
