# Generated by Django 4.0 on 2022-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFishapp', '0006_fview_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fview_contact',
            name='message',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
