# Generated by Django 4.0 on 2022-01-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webFishapp', '0007_alter_fview_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='fwcart',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webFishapp.freg'),
        ),
    ]
