# Generated by Django 4.0 on 2022-01-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0006_rfish'),
        ('webFishapp', '0010_rename_name_fcheckout_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcheckout',
            name='productid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishapp.pfish'),
        ),
    ]
