# Generated by Django 4.0 on 2022-01-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webFishapp', '0011_fcheckout_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcheckout',
            name='productid',
        ),
    ]
